theme = "slick"
icons = "awesome"


[[block]]
block = "focused_window"
max_width = 50
show_marks = "visible"

[[block]]
block = "nvidia_gpu"
label = "RTX 2070"
show_memory = false
show_clocks = false
show_temperature = true
interval = 1
  

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_total_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"